package com.acciobuild.project.domain.event;

import lombok.Getter;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Base abstract class representing domain events generated by Project Service.
 */
@Getter
public abstract class ProjectDomainEvent {

    private final String eventType;
    private final UUID organizationId;
    private final LocalDateTime timestamp;
    private final String correlationId;

    /**
     * Constructs the base event.
     */
    protected ProjectDomainEvent(String eventType, UUID organizationId, String correlationId) {
        this.eventType = eventType;
        this.organizationId = organizationId;
        this.timestamp = LocalDateTime.now();
        this.correlationId = correlationId;
    }
}
